### PR TITLE
Routes for cycles and gamemodes

### LINKED ISSUE #3: This one query will fail if the hierarchy is taken by another role
`RoleController@update`: check will succeed and update will fail if the hierarchy level is already taken as is by another role because the DB field is unique

also if it fails it'll just redirect to a blank page cuz it's only going to do something in the last line
```php
public function update($id, Request $request) 
	{
		$role = Role::findOrFail($id);
		$this->authorize('update', $role);
		$request->validate([
			'name' => 'required',
			'description' => 'required',
			'color' => 'required|max:6',
			'hierarchy' => 'required',
		]);
		$role->name         = e($request->name);
		$role->description  = e($request->description);
		$role->color 		= e($request->color);
		$role->hierarchy    = e($request->hierarchy);
		if ($role->save()) return back();

	}
```

### PR DESCRIPTION
**Pull request by Okorin**
fixes #3 by redoing the validation

ToDo
- [x] view all cycles
- [x] create cycles for organizers
- [x] note to self to never implement anything to delete cycles with
- [x] edit cycles
- [x] populate participant table with dummy data
- [x] ability to view those based on cycles / users / gamemode

### CODE REVIEW

File: app/Http/Controllers/CycleController.php [hunk 1]
```diff
@@ -0,0 +1,159 @@
...
+    }
+
+    protected function doBasicFormCheck(Request $request) {
+        $request->validate([
+            'mentorSignupsStart' => 'required|date_format:Y-m-d',
+            'mentorSignupsEnd' => 'required|date_format:Y-m-d',
+            'menteeSignupsStart' => 'required|date_format:Y-m-d',
+            'menteeSignupsEnd' => 'required|date_format:Y-m-d',
+            'cycleStart' => 'required|date_format:Y-m-d',
+            'cycleEnd' => 'required|date_format:Y-m-d',
```
Comment (Okorin) [inline app/Http/Controllers/CycleController.php]: name field needs to be on here to check for max length of 25 in db

File: app/Http/Controllers/CycleController.php [hunk 2]
```diff
@@ -0,0 +1,159 @@
...
+        return view('cycle.create');
+    }
+
+    /**
+     * Store a newly created resource in storage.
+     *
+     * @param  \Illuminate\Http\Request  $request
+     * @return \Illuminate\Http\Response
+     */
+    public function store(Request $request)
```
Comment (Okorin) [inline app/Http/Controllers/CycleController.php]: this needs to be able to deal with name / active

File: resources/views/cycle/create.blade.php [hunk 3]
```diff
@@ -0,0 +1,90 @@
+@extends('layouts.master')
+
+@section('title', 'Define a new Cycle')
+
+@section('content')
```
Comment (Okorin) [inline resources/views/cycle/create.blade.php]: needs same things as edit
